services:
  skewl:
    build:
      context: .
      dockerfile: apps/client/Dockerfile
    image: client
    ports:
      - "5173:5173"
    restart: unless-stopped

  skewl-backend:
    network_mode: host
    build:
      context: .
      dockerfile: apps/server/Dockerfile
    image: server
    ports:
      - "4000:4000"
    restart: unless-stopped
    environment:
      NODE_ENV: production
      PORT: "4000"
    depends_on:
      - skewl
